### ISSUE TITLE
Can't send data because WebSocket is not opened.

### ISSUE THREAD

**Issue by apadilla83** [skydiver/ewelink-api#118]
I have this menssage on websocket connection, but the socket sitll get data and working

 Error: Can't send data because WebSocket is not opened.
11/06/2020 08:26:06:     at exports.throwIf (/usr/src/node/node_modules/websocket-as-promised/src/utils.js:4:11)
11/06/2020 08:26:06:     at WebSocketAsPromised.send (/usr/src/node/node_modules/websocket-as-promised/src/index.js:248:5)
11/06/2020 08:26:06:     at Timeout._onTimeout (/usr/src/node/node_modules/ewelink-api/src/mixins/openWebSocket.js:42:16)
11/06/2020 08:26:06:     at listOnTimeout (internal/timers.js:549:17)
11/06/2020 08:26:06:     at processTimers (internal/timers.js:492:7)

**Comment by nodoubtman** [comment]
same error here :(

**Comment by evikhorev** [comment]
same error here :(

**Comment by evikhorev** [comment]
Dec 03 09:33:39 ubuntu nodejs-example[29877]: (node:29877) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function with>
Dec 03 09:35:39 ubuntu nodejs-example[29877]: (node:29877) UnhandledPromiseRejectionWarning: Error: Can't send data because WebSocket is not opened.
Dec 03 09:35:39 ubuntu nodejs-example[29877]:     at exports.throwIf (/opt/node/node_modules/websocket-as-promised/src/utils.js:4:11)
Dec 03 09:35:39 ubuntu nodejs-example[29877]:     at WebSocketAsPromised.send (/opt/node/node_modules/websocket-as-promised/src/index.js:248:5)
Dec 03 09:35:39 ubuntu nodejs-example[29877]:     at Timeout.setInterval [as _onTimeout] (/opt/node/node_modules/ewelink-api/src/mixins/openWebSocket.js:39:17)
Dec 03 09:35:39 ubuntu nodejs-example[29877]:     at ontimeout (timers.js:436:11)
Dec 03 09:35:39 ubuntu nodejs-example[29877]:     at tryOnTimeout (timers.js:300:5)
Dec 03 09:35:39 ubuntu nodejs-example[29877]:     at listOnTimeout (timers.js:263:5)
Dec 03 09:35:39 ubuntu nodejs-example[29877]:     at Timer.processTimers (timers.js:223:10)
Dec 03 09:35:39 ubuntu nodejs-example[29877]: (node:29877) UnhandledPromiseRejectionWarning: Unhandled pr
