### ISSUE TITLE
Error sending a Request

### ISSUE THREAD

**Issue by andres934** [skydiver/ewelink-api#4]
Hello, just implement the library and tried to make a request and it gaves me an error, i don't know what could i miss..

 the response was:

```
Error: getaddrinfo EAI_AGAIN us-api.coolkit.cc:8080
    at new RequestError (/srv/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/srv/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/srv/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/srv/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/srv/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

i just install the package with npm and add the getDevices example code, by the way, i'm using it in Firebase Cloud Functions, here is the code:

```
const ewelink = require('ewelink-api');

exports.getMyDevices = https.onRequest( async (req, res) => {
    const myEmail = req.body.email;
    const myPassword = req.body.password;

    const conn = new ewelink({
        email: myEmail,
        password: myPassword,
      });
    
    /* get all devices */
    const devices = await conn.getDevices();
    res.status(200).send(devices);
});
```

**Comment by andres934** [comment]
and no, haven't exceed the quota lol

**Comment by skydiver** [comment]
Hello @andres934 

The error is because you can't connect to ewelink server.

As far as i know, with Firebase free version you can't connect to "not Google cloud" services.


![image](https://user-images.githubusercontent.com/578784/61422911-23508480-a8e4-11e9-9d03-c6fdd2c1285e.png)

https://firebase.google.com/pricing/
