### ISSUE TITLE
WebSocket not closed error

### ISSUE THREAD

**Issue by viktorbk** [skydiver/ewelink-api#65]
When the hearbeat interval function runs it does not check if the websocket is open and that often creates error like this one:
`(node:914) UnhandledPromiseRejectionWarning: Error: Can't send data because WebSocket is not opened.
    at exports.throwIf (/root/nodejs/ewelink-sserver/node_modules/websocket-as-promised/dist/index.js:3470:11)
    at WebSocketAsPromised.send (/root/nodejs/ewelink-sserver/node_modules/websocket-as-promised/dist/index.js:554:7)
    at Timeout._onTimeout (/root/nodejs/ewelink-sserver/node_modules/ewelink-api/mixins/websocket/openWebSocketMixin.js:38:17)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)`

Please add the check "if (wsp.isOpened)" to the interval function (line 37 in openWebSocketMixin):
```    
   setInterval(async () => {
      if (wsp.isOpened) {
        await wsp.send('ping');
      }
    }, heartbeat);

**Comment by foulek57** [comment]
Hi have the same problem, will be nice if you can change this

**Comment by ttz642** [comment]
See #25 for some other suggestions on how to trap errors.

If the socket isn't open then it should return an error allowing the application to re-open the socket.

**Comment by ttz642** [comment]
I've added extra code to detect and report this issue back and terminate the pp allowing the process manager to re-start.

```
$ pm2 ls
┌─────┬──────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name         │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ events       │ default     │ 1.0.0   │ fork    │ 8650     │ 30h    │ 2    │ online    │ 0.5%     │ 82.7mb   │ sonoff   │ disabled │
│ 2   │ scheduler    │ default     │ 1.0.0   │ fork    │ 3892     │ 2D     │ 0    │ online    │ 0.5%     │ 66.0mb   │ sonoff   │ disabled │
│ 1   │ www          │ default     │ 1.0.0   │ fork    │ 3876     │ 2D     │ 0    │ online    │ 0.5%     │ 60.6mb   │ sonoff   │ disabled │
└─────┴──────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
```
Here you can see the event listener has been restarted twice because the connection was closed.

I'll post the code later.

**Comment by ttz642** [comment]
core event handler:

```
    socket = await connection.openWebSocket(async data => {
        try{
            if (data.action == "socket"){
                switch (data.message) {
                case "opened":  console.log(new Date().toISOString(),'| Socket opened...');
                                break;
                case "pong":    //console.log(new Date().toISOString(),'| Keepalive received...');
                                break;
                case "timeout": console.log(new Date().toISOString(),'| Socket timed out...');
                case "closed":  console.log(new Date().toISOString(),'| Socket closed...');
                                console.log(new Date().toISOString(),'| Gracefully close and re-start...');
                case "error":   socket.removeAllListeners();
                                socket.close();
                                process.exit(1);
                                throw new Error("timeout, closed or error...");
                                break;
                default:        console.log(new Date().toISOString(),'| socket action not supported,',"Invalid data::",JSON.stringify(data,null,4));
                                throw new Error("unknown...");
                }
            }else{
                try {
                    if(data.action == "update"){
                        if((data.deviceid != null)&&(data.params.switch != null)){
                            console.log(new Date().toISOString(),'| device',data.deviceid,'alias',soo.localcache[data.deviceid].alias,'switch',data.params.switch);
                            post(www+'switch/'+data.deviceid+'/'+data.params.switch,'');
                        }
                    }
                } catch (error) {
                    console.log(new Date().toISOString(),'| Caught error:',JSON.stringify(error));
                }
            }
        } catch (error) {
            console.log(new Date().toISOString(),'| Error returned:',error);
            console.log(JSON.stringify(data,null,4));
            socket.removeAllListeners();
            socket.close();
            process.exit(1);
            throw new Error(error.message);
        }
    }).catch((error) => {
        // Handle the error!
        console.log(new Date().toISOString(),'| Final catch of Error returned:',error);
        socket.removeAllListeners();
        socket.close();
        process.exit(1);
        throw new Error(error.message);
    });
```

This code relies on enhancements to ewelink-api/mixins/websocket/openWebSocketMixin.js

```
/*  ORIGINAL code::
    await wsp.open();
    await wsp.send(payloadLogin);
    setInterval(async () => {
      await wsp.send('ping');
    }, heartbeat);
*/  // replace with
    wsp.onOpen.addListener(() => {
        callback({"action": "socket" , "message" : "opened"});
    });
    wsp.onClose.addListener(event => {
        callback({"action": "socket" , "message" : "closed"});
    });
    wsp.onError.addListener(event => {
        callback({"action": "socket" , "message" : "error"});
    });
    await wsp.open();
    await wsp.send(payloadLogin);

    setInterval(async () => {
      var tsdelta = tsout - tsin;
      //console.log("tsdelta",tsdelta);
      if(wsp.isClosed || wsp.isClosing){
        callback({"action": "socket" , "message" : "closed"});
      }
      if(tsdelta >= (period*5)){
        //if we haven't had a reply to one of the three outstanding ping's
        //in last 5 heartbeats were probably not connected anymore, thus timeout
        callback({"action": "socket" , "message" : "timeout"});
      }
      tsout =  Math.floor(Date.now()/1000);
      if(tsdelta < (3 * period)){
        wsp.send('ping');//await
        //var date = new Date().toUTCString();
        //console.log("### keepalive sent at:",date);
      }
    }, heartbeat);
// to here !
```

**Comment by saqib-ahmed** [comment]
Any update on this issue?

**Comment by pierred510** [comment]
Hi
I still have this problem with the last version; Impossible to listen ewelink events with a long time
fix possible ?

**Comment by LiYuanBr** [comment]
Hi.
I solve this issue by creating an auto restart mode in the [openWebSocket.js](https://github.com/skydiver/ewelink-api/blob/5a07f6b6152d603c71266012177cc4b47d533bf9/src/mixins/openWebSocket.js) when it closes the connection.

The **ewelink-api/src/mixins/openWebSocket.js** in this repository:
https://github.com/skydiver/ewelink-api/blob/5a07f6b6152d603c71266012177cc4b47d533bf9/src/mixins/openWebSocket.js#L38-L40

I changed to get credentials and try to restart the WebSocket:
```
setInterval(async () => {
      try {
        await wsp.send('ping');
      } catch (error) {
        console.error(`openWebSocket.js: ${error}`);
        console.log(`openWebSocket.js: Reconnecting...`);
        const auth = await this.getCredentials();
        const payloadLogin = wssLoginPayload({
          at: auth.at,
          apiKey: auth.user.apikey,
          appid: this.APP_ID,
        });
        await wsp.open();
        await wsp.send(payloadLogin);
      }
    }, heartbeat);
```
This way it closes the connection but doesn't close the process. It tries to connect again.

I'm still learning about JavaScript and I know that this code is very primitive, however, it solved my connection problem.
Feel free to make some changes.
